"""Compatibility layer for Gardener state tracking.

Prefer importing from db.py, git_state.py, file_state.py, and provenance.py.
"""

from db import SCHEMA, SCHEMA_VERSION, get_db_connection, init_db
from file_state import (
    ChangedFile,
    FileInfo,
    ReconcileRun,
    classify_location,
    cleanup_stale_files,
    compute_file_hash,
    generate_maintenance_tasks,
    get_all_current_files,
    get_changes_since_sha,
    get_dirty_summary,
    get_file_counts_by_location,
    get_file_state,
    get_files_by_location,
    record_reconcile_run,
    remove_file_state,
    run_reconcile,
    update_file_state,
)
from git_state import (
    CommitInfo,
    RepoState,
    check_repo_identity,
    cleanup_old_commits,
    get_current_branch,
    get_current_head,
    get_dirty_files,
    get_processed_commits,
    get_repo_root_hash,
    get_repo_state,
    record_processed_commit,
    update_last_processed_sha,
    update_last_seen_sha,
    update_repo_root_hash,
)
from provenance import (
    PROVENANCE_EXTERNAL_CLAUDE,
    PROVENANCE_EXTERNAL_MCP,
    PROVENANCE_EXTERNAL_SCRIPT,
    PROVENANCE_GARDENER,
    PROVENANCE_MANUAL,
    EditProvenance,
    format_commit_message,
    get_file_provenance,
    get_provenance_by_source,
    parse_commit_source,
    record_provenance,
)

__all__ = [
    "SCHEMA",
    "SCHEMA_VERSION",
    "get_db_connection",
    "init_db",
    "ChangedFile",
    "FileInfo",
    "ReconcileRun",
    "classify_location",
    "cleanup_stale_files",
    "compute_file_hash",
    "generate_maintenance_tasks",
    "get_all_current_files",
    "get_changes_since_sha",
    "get_dirty_summary",
    "get_file_counts_by_location",
    "get_file_state",
    "get_files_by_location",
    "record_reconcile_run",
    "remove_file_state",
    "run_reconcile",
    "update_file_state",
    "CommitInfo",
    "RepoState",
    "check_repo_identity",
    "cleanup_old_commits",
    "get_current_branch",
    "get_current_head",
    "get_dirty_files",
    "get_processed_commits",
    "get_repo_root_hash",
    "get_repo_state",
    "record_processed_commit",
    "update_last_processed_sha",
    "update_last_seen_sha",
    "update_repo_root_hash",
    "PROVENANCE_EXTERNAL_CLAUDE",
    "PROVENANCE_EXTERNAL_MCP",
    "PROVENANCE_EXTERNAL_SCRIPT",
    "PROVENANCE_GARDENER",
    "PROVENANCE_MANUAL",
    "EditProvenance",
    "format_commit_message",
    "get_file_provenance",
    "get_provenance_by_source",
    "parse_commit_source",
    "record_provenance",
]
